name: luchem
dependencies:
    - faunus=2
    - ipywidgets
    - jupyterlab
    - matplotlib
    - mdtraj
    - nglview
    - numpy
    - pandas
    - python=3
    - ruff
    - scipy<1.12
    - seaborn
    - sympy
    - xlrd
