name: luchem
channels:
    - conda-forge
dependencies:
    - python=3
    - numpy
    - seaborn
    - matplotlib
    - scipy<1.12
    - pandas
    - mdtraj
    - faunus
    - ipywidgets
    - sympy
    - nglview
    - xlrd
